backend:
  name: github
  branch: qa
  repo: RobTF9/gatsby-portfolio

media_folder: /static/img
public_folder: /img

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Client", name: "client", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Color", name: "color", widget: "string" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Outline", name: "outline", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "experience"
    label: "Experience"
    folder: "src/experience"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "From", name: "from", widget: "date", format: "MM YY" }
      - { label: "To", name: "to", widget: "date", format: "MM YY" }
      - { label: "Current", name: "current", widget: "boolean", default: false }
      - { label: "Role", name: "role", widget: "string" }
      - { label: "Order", name: "order", widget: "number" }
      - { label: "Description", name: "description", widget: "markdown" }
