backend:
  name: github
  branch: master
  repo: RobTF9/gatsby-portfolio

media_folder: /static/img
public_folder: /img

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Client", name: "client", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Color", name: "color", widget: "string" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  
    - name: "experience"
    label: "Experience"
    folder: "src/experience"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "From", name: "from", widget: "datetime" }
      - { label: "To", name: "to", widget: "datetime" }
      - { label: "Company", name: "company", widget: "string" }
      - { label: "Role", name: "role", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }

